const StudentActionTypes = {
  CREATE_STUDENT_COURSE_DETAILS_START: 'CREATE_STUDENT_COURSE_DETAILS_START',
  CREATE_STUDENT_COURSE_DETAILS_SUCCESS: 'CREATE_STUDENT_COURSE_DETAILS_SUCCESS',
  CREATE_STUDENT_COURSE_DETAILS_FAILURE: 'CREATE_STUDENT_COURSE_DETAILS_FAILURE',
  UPDATE_STUDENT_COURSE_DETAILS_START: 'UPDATE_STUDENT_COURSE_DETAILS_START',
  UPDATE_STUDENT_COURSE_DETAILS_SUCCESS: 'UPDATE_STUDENT_COURSE_DETAILS_SUCCESS',
  UPDATE_STUDENT_COURSE_DETAILS_FAILURE: 'UPDATE_STUDENT_COURSE_DETAILS_FAILURE',
  FETCH_STUDENT_DETAILS_START: 'FETCH_STUDENT_DETAILS_START',
  FETCH_STUDENT_DETAILS_SUCCESS: 'FETCH_STUDENT_DETAILS_SUCCESS',
  FETCH_STUDENT_DETAILS_FAILURE: 'FETCH_STUDENT_DETAILS_FAILURE',
  CREATE_STUDENT_DETAILS_START: 'CREATE_STUDENT_DETAILS_START',
  CREATE_STUDENT_DETAILS_SUCCESS: 'CREATE_STUDENT_DETAILS_SUCCESS',
  CREATE_STUDENT_DETAILS_FAILURE: 'CREATE_STUDENT_DETAILS_FAILURE',
  UPDATE_STUDENT_DETAILS_START: 'UPDATE_STUDENT_DETAILS_START',
  UPDATE_STUDENT_DETAILS_SUCCESS: 'UPDATE_STUDENT_DETAILS_SUCCESS',
  UPDATE_STUDENT_DETAILS_FAILURE: 'UPDATE_STUDENT_DETAILS_FAILURE',
  UPDATE_STUDENT_FUNDS_START: 'UPDATE_STUDENT_FUNDS_START',
  UPDATE_STUDENT_FUNDS_SUCCESS: 'UPDATE_STUDENT_FUNDS_SUCCESS',
  UPDATE_STUDENT_FUNDS_FAILURE: 'UPDATE_STUDENT_FUNDS_FAILURE',
}

export default StudentActionTypes;
