const SystemActionTypes = {
  FETCH_USERS_START: 'FETCH_USERS_START',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  UPDATE_USER_ROLE_START: 'UPDATE_USER_ROLE_START',
  UPDATE_USER_ROLE_SUCCESS: 'UPDATE_USER_ROLE_SUCCESS',
  UPDATE_USER_ROLE_FAILURE: 'UPDATE_USER_ROLE_FAILURE',
}

export default SystemActionTypes;
