import React from 'react';
import { Link } from 'react-router-dom';

import * as ROUTES from './../../constants/routes';

import './terms-page.styles.scss';

const TermsPage = () => (
  <div className='container px-xs mt-xs'>
    <p style={{textAlign: 'center'}}><strong>Native Talk Inc.</strong></p>
    <p style={{textAlign: 'center'}}><strong>User Agreement</strong></p>
    <p>Last Updated: November 16, 2020</p>
    <p>Welcome to Native Talk Inc. (“Native Talk,” “we,” “us,” or “our”), application and website! We connect individuals who want to learn a language (“Students”) with a native speaker who can help them learn (“Tutors”) for real time video chat language tutoring sessions (“Tutoring Services”). This User Agreement (the “Agreement”) applies to Students and Tutors, and where Students are minors/children under the age of 13, their parent or legal guardian (collectively, “Users,” “you,” or “your”), whether through our websites, nativetalk.live (the “Sites”) or Native Talk or Native Talk Kids mobile device applications (the “Apps,” together with Sites, “the Platform”).</p>
    <p><strong>PLEASE READ THIS AGREEMENT CAREFULLY. THIS AGREEMENT PROVIDES THAT ALMOST ALL DISPUTES BETWEEN YOU AND Native Talk ARE SUBJECT TO BINDING ARBITRATION AND CONTAINS A WAIVER OF CLASS AND COLLECTIVE ACTION RIGHTS AND ANY RIGHT TO A JURY TRIAL AS DETAILED IN THE <a href="#eligibility">ARBITRATION AND CLASS ACTION WAIVER SECTION BELOW</a>a. BY ENTERING THIS AGREEMENT, YOU GIVE UP YOUR RIGHT TO SUE IN COURT, HAVE YOUR CLAIMS HEARD BY A JURY, AND TO BE PART OF A CLASS OR COLLECTIVE ACTION, TO RESOLVE THESE DISPUTES, AS EXPLAINED IN MORE DETAIL IN THAT SECTION.</strong></p>
    <p>PLEASE REVIEW THIS AGREEMENT IN ITS ENTIRETY. BY ACCESSING THE PLATFORM OR REGISTERING FOR A USER ACCOUNT, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THIS AGREEMENT, INCLUDING, AS APPLICABLE, THE ARBITRATION AND CLASS ACTION PROVISIONS AND VIDEO RECORDING PROVISIONS, AND THAT YOU ARE BINDING YOU, YOUR HEIRS, ASSIGNS, AND SUCCESSORS TO THIS AGREEMENT. IF YOU ARE AGREEING TO THIS AGREEMENT ON BEHALF OF AN ORGANIZATION OR ENTITY, YOU REPRESENT AND WARRANT THAT YOU ARE AUTHORIZED TO AGREE TO THIS AGREEMENT ON THAT ORGANIZATION OR ENTITY’S BEHALF AND BIND THEM TO THIS AGREEMENT (IN WHICH CASE, THE REFERENCES TO “YOU” AND “YOUR” IN THIS AGREEMENT, EXCEPT FOR IN THIS SENTENCE, REFER TO THAT ORGANIZATION OR ENTITY).</p>
    <p>IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, YOU MAY NOT ACCESS OR USE THE PLATFORM.</p>
    <ol start="1">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}><a href="#" id="eligibility">Eligibility</a></span></li>
    </ol>
    <p>You may use the Platform only if you can form a binding contract with Native Talk, and only in compliance with this Agreement and all applicable local, state, national, and international laws, rules, and regulations.</p>
    <p>If you are a Student, you represent that you are over the age of thirteen (13) years old in the United States or sixteen (16) years old in all other jurisdictions&nbsp; (the “Minimum Age”). If you are a Student over the Minimum Age, but under the legal age of majority, you may not use the Platform unless your parent or legal guardian has provided Native Talk verifiable consent and agreed to this Agreement.</p>
    <p>If you are a Tutor, you represent that you are over the age of 18.</p>
    <p>If Native Talk has previously prohibited you from accessing or using the Platform, you are not permitted to access or use the Platform.</p>
    <ol start="2">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Additional Terms and Guidelines</span></li>
    </ol>
    <p><em>Tutor Addendum.</em> The <Link to={ROUTES.ADDENDUM} target="_blank" rel="noopener noreferrer">Tutor Addendum</Link>, incorporated herein by reference, also applies to Tutors in their access, registration, or other use of the Platform.</p>
    <p><em>Guidelines</em>. When using the Platform, you are subject to any additional posted guidelines or rules applicable to specific services, offers, and features (the “Guidelines”). All such Guidelines are incorporated by reference into this Agreement. The <Link to={ROUTES.PRIVACY_POLICY} target="_blank" rel="noopener noreferrer">Native Talk Kids Children’s Privacy Policy</Link> is also incorporated into this Agreement to the extent you are using the Native Talk Kids Platform and Tutoring Services (“Native Talk Kids”) as a Student. Note, when Native Talk Kids is used, both the Native Talk Privacy Policy and the Native Talk Kids Privacy Policy apply to certain pages or functions performed by an adult on the Native Talk Kids site, such as when providing parental consent.</p>
    <ol start="3">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Data Privacy</span></li>
    </ol>
    <p><em>Privacy Policy</em>. Native Talk’s <Link to={ROUTES.PRIVACY_POLICY} target="_blank" rel="noopener noreferrer">Privacy Policy</Link> is incorporated into this Agreement. Please read this notice carefully for details relating to the collection, use, and disclosure of your personal information.</p>
    <p><em>Tutors are Data Controllers</em>. Tutors will receive Personal Data of Students in the course of Tutors providing and Students receiving Tutoring Services. As used in this Section 3, Personal Data shall have the meaning assigned to the terms “personal data” or “personal information” under applicable data protection laws, such as the General Data Protection Regulation (EU 2016/679) (“GDPR”) or the California Consumer Privacy Act (“CCPA”). With respect to any Personal Data obtained by Tutor pursuant to this Agreement, Tutor agrees to independently comply with its obligations as a “controller” under the GDPR, and a “business” under the CCPA, to the extent applicable to Tutor.</p>
    <ol start="4">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Modifications</span></li>
    </ol>
    <p>Native Talk may make modifications to this Agreement (“Changes”) at any time. Except as explicitly provided in this Agreement, such Changes will be effective as to existing Users after Native Talk provides notice of the Changes, either through the Platform user interface or sent to the e-mail address associated with your User account; and when you opt-in or otherwise expressly agree to the Changes or a version of this Agreement incorporating the Changes. If you provide written notice that you do not accept a proposed Change or decline to expressly agree to a proposed Change, Native Talk may terminate this Agreement and your use of the Platform.</p>
    <ol start="5">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Account Registration and Use</span></li>
    </ol>
    <p><em>Student Registration</em>. The Platform allows Students to request and engage in a video chat session with a Tutor for purposes of learning and practicing conversation skills in the language of a Student’s choice (a “Session”). To access a Session in our Tutoring Services, you must register and create an account through the Platform. Registration may require you to: (i) create a unique user name and password, (i) provide an e-mail address, (iii) indicate your current country of domicile, (iv) indicate your native language, (v) indicate the language you wish to practice, and (vi) indicate your gender. Note that Native Talk does not have access to your payment card information, as we use a third-party payment processor to receive and process payments.</p>
    <p><em>Tutor Registration</em>. To use the Platform and offer tutoring services to Students, Tutors must register and create an account through the App or the Site. As part of the registration process, we may require a Tutor to: (i) create a unique user name and password, (ii) provide an e-mail address, (iii) indicate Tutor’s current country of domicile, (iv) indicate Tutor's native language, (v) indicate the language for which Tutor wishes to conduct the Services, (vi) indicate Tutor’s gender, (vi) indicate Tutor’s PayPal account, and (vii) indicate that Tutor is at least eighteen (18) years of age.</p>
    <p><em>Registration Accuracy</em>. You agree that the information you provide, at all times, will be true, accurate, current, and complete. You also agree that you will ensure that this information is kept confidential, accurate and up-to-date at all times.</p>
    <p><em>Password</em>. When you register, you will be asked to provide a password. You are solely responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account. If you have reason to believe that your account is no longer secure (for example, in the event of a loss, theft or unauthorized disclosure or use of your account ID or password), you will immediately notify Native Talk. You may be liable for the losses incurred by Native Talk or others due to any unauthorized use of your account.</p>
    <p><em>Personal Use</em>. Except as provided herein, Native Talk accounts may only be used by the User who registered for that account. Minutes purchased by a Student may only be used by that Student in that Student’s account. You agree not to share your user name and password or otherwise permit any other person to access or use your Native Talk account. Under no circumstances may a Tutor allow other individuals to use the Tutor’s account to perform any Services.</p>
    <ol start="6">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Native Talk is a Marketplace Provider</span></li>
    </ol>
    <p>You understand that Native Talk is not in the business of providing tutoring services. Native Talk provides an online marketplace that connects Students with Tutors.</p>
    <p><em>Tutors are Independent Contractors</em>. You acknowledge that Tutors are independent contractors operating an independent business enterprise who use the Platform to offer and provide Tutoring Services to Students. Native Talk is not an employer of, or joint employer or integrated or single enterprise with any Tutor. You acknowledge and agree that Native Talk has no responsibility for, control over, or involvement in the scope, nature, quality, character, timing or location of any work or services performed by Tutor, including any work or services that any individual affiliated with the Tutor may provide, either as an employee, independent contractor, or otherwise. Student further represents, acknowledges, and warrants that throughout the Term it shall at all times treat Tutor as independent contractors and that Student will take no action that is inconsistent with such classification. Native Talk is under no obligation to ensure any Session is completed to Student’s satisfaction.</p>
    <p><em>Tutors Provide Materials</em>. You understand that, except as otherwise specifically agreed between Student and Tutor, Tutor will provide all equipment, tools, materials, and labor that he or she needs to perform the Tutoring Services agreed to with Student and that Native Talk will provide no equipment, tools, materials, or labor that may be needed to perform the Tutoring Services under this Agreement. Native Talk will, however, in its discretion, provide both Student and Tutor with access to the Platform to facilitate access to available, optional support resources and materials.</p>
    <ol start="7">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Rules and Prohibitions</span></li>
    </ol>
    <p>You may not:</p>
    <ul>
      <li>access or use the Platform for any purpose that is unlawful or prohibited by this Agreement;</li>
      <li>use the Platform in any manner that in our sole discretion could damage, disable, overburden, or impair it or interfere with any other party’s use of the Platform;</li>
      <li>intentionally interfere with or damage the operation of the Platform, or any User’s enjoyment of it, by any means, including uploading or otherwise disseminating viruses, worms, or other malicious code;</li>
      <li>remove, circumvent, disable, damage or otherwise interfere with any security-related features of the Platform, features that prevent or restrict the use or copying of any content accessible through the Platform, or features that enforce limitations on the use of the Platform;</li>
      <li>attempt to gain unauthorized access to the Platform, or any part of it, other accounts, computer systems or networks connected to the Platform, or any part of it, through hacking, password mining or any other means or interfere or attempt to interfere with the proper working of the Platform or any activities conducted on the Platform;</li>
      <li>obtain or attempt to obtain any materials or information through any means not intentionally made available through the Platform;</li>
      <li>use any robot, spider, scraper, or other automated means to access the Platform for any purpose without our express written permission or bypass our robot exclusion headers or other measures we may use to prevent or restrict access to the Platform;</li>
      <li>utilize any trademark, logo, or other Native Talk materials without our express written consent, including through framing techniques or in meta tags of “hidden text”;</li>
      <li>modify the Platform in any manner or form, or use modified versions of the Platform, including (without limitation) for obtaining unauthorized access to the Platform;</li>
      <li>create more than one account, use another person’s account without authorization, impersonate any person or entity; or forge or manipulate headers or identifiers to disguise the origin of any content transmitted through the Platform;</li>
      <li>in any way violate any copyrights, trade secrets, or other rights of any third party, including privacy or publicity rights;</li>
      <li>spam anyone;</li>
      <li>post advertisements or conduct any commercial solicitation purposes without Native Talk’s written permission;</li>
      <li>engage in conduct or post content that is libelous, defamatory, abusive, threatening, harassing, hateful, obscene, offensive, humiliating to other people (publicly or otherwise), or otherwise violates any law or right of Native Talk or any third party;</li>
      <li>share other people's private or personally identifiable information without their express authorization and permission; or</li>
      <li>attempt to indirectly undertake any of the foregoing.</li>
    </ul>
    <p>If you are a Student, you further agree to only engage in Sessions for the sole purpose of learning or practicing your language skills. If you are a Tutor, you further agree to only engage in Sessions for the sole purpose of teaching language skills to a Student.</p>
    <ol start="8">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>User Content</span></li>
    </ol>
    <p>We may allow you to submit, post, upload, publish, submit, transfer, link, display, or otherwise make available (hereinafter, “post”) information, text, graphics, photograph, audio, video, postings, reviews, designs, inventions, or other materials on the Platform (“User Content”) that may or may not be viewable by other Users. You retain ownership of all intellectual property rights you have in the User Content you post on the Platform.</p>
    <p>By posting User Content on or through the Platform, you grant Native Talk a worldwide, irrevocable, perpetual, non-exclusive, transferable, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display, distribute, and otherwise exploit such User Content in any format or medium now known or developed in the future for Native Talk’s business purposes or as required by law or legal process. In the interest of clarity, the license granted to Native Talk shall survive termination of the Platform or your account. Notwithstanding the license granted to Native Talk in User Content and for avoidance of doubt, our use and retention of your personal data, including any that is contained in User Content, shall also be governed by and comply with the <Link to={ROUTES.PRIVACY_POLICY} target="_blank" rel="noopener noreferrer">Native Talk Privacy Policy</Link>. You represent, warrant and agree that you have the necessary rights to grant us the license described in this Section for any User Content that you post. You agree that this license includes the right for other Users with permitted access to your User Content (e.g. Tutors or Students) to use your User Content in conjunction with participation in the Platform and as permitted through the functionality of the Platform.</p>
    <p>You shall be solely responsible for your own User Content and the consequences of posting or publishing it, and you agree that we are only acting as a passive conduit for your online distribution and publication of your User Content. You understand that Native Talk does not control, and is not responsible for, User Content, and that by using the Platform, you may be exposed to User Content from other Users that is offensive, indecent, inaccurate, misleading, or otherwise objectionable. To report any inappropriate activity, please e-mail Native Talk at <a href="mailto:support@nativetalk.live" target="_blank" rel="noopener noreferrer"><span style={{color: '#0563c1'}}>help@nativetalk.live</span></a>. Please also note that User Content may contain typographical or other inadvertent errors or inaccuracies.</p>
    <p>Native Talk reserves the right in its sole discretion to remove or disable access to any User Content from the Platform, suspend or terminate your account at any time, or pursue any other remedy or relief available under equity or law if you post any User Content that violates this Agreement or we consider to be objectionable for any reason. You agree that Native Talk reserves the right to monitor User Content (but does not assume the obligation), and you understand it remains your sole responsibility to monitor your User Content and ensure that your User Content is accurate and consistent with your representations and warranties in this Agreement.</p>
    <p>Native Talk reserves the right to access, read, preserve, and disclose any information as we reasonably believe is necessary to (i) satisfy any applicable law, regulation, legal process, or governmental request, (ii) enforce this Agreement, including investigation of potential violations hereof, (iii) detect, prevent, or otherwise address fraud, security, or technical issues, (iv) respond to User support requests, or (v) protect the rights, property or safety of Native Talk, its Users and the public.</p>
    <ol start="9">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>License to Use the Platform</span></li>
    </ol>
    <p>Subject to your compliance with the terms of this Agreement, Native Talk grants you a limited, non-exclusive, non-assignable, non-sub-licensable, revocable, license to access and use the Platform as it is provided to you by Native Talk solely for your personal, noncommercial use and only in connection with your access to and participation in the Platform and only in a manner that complies with all legal requirements that apply to you or your use of the Platform, including those relating to data security and data privacy, such as those specified in the Native Talk Privacy Policy. Native Talk may revoke this license at any time, in its sole discretion. Upon such revocation, you must promptly destroy all materials downloaded or otherwise obtained from the Platform, as well as all copies of such materials, whether made in accordance with this Agreement or otherwise.</p>
    <p>You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast, or otherwise exploit the Platform or content available therein, except as expressly permitted in this Agreement. The Platform or content available therein are provided to you AS IS. If you download or print a copy of any content available on the Platform for personal use, you must retain all copyright and other proprietary notices contained thereon. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Native Talk or its licensors, except for the licenses and rights expressly granted in this Agreement.</p>
    <ol start="10">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Ownership and Proprietary Rights</span></li>
    </ol>
    <p>The Platform is owned and operated by Native Talk. The videos, content, visual interfaces, information, graphics, design, compilation, computer code, products, software, services, and all other elements of the Platform (“Native Talk Materials”) are protected by United States copyright, trade dress, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws. All Native Talk Materials are the property of Native Talk or its subsidiaries or affiliated companies and/or third-party licensors. All trademarks, service marks, and trade names are proprietary to Native Talk or its affiliates and/or third-party licensors. Except as expressly authorized by Native Talk, you agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorized use of the Native Talk Materials.</p>
    <p>Any feedback, comments, questions, or suggestions (collectively, “Feedback”) you may provide regarding the Platform is entirely voluntary and we will be free to use such feedback, comments or suggestions without any obligation to you. By sending us any Feedback, you further (i) agree that we are under no obligation of confidentiality, express or implied, with respect to the Feedback; (ii) acknowledge that we may have something similar to the Feedback already under consideration or in development; (iii) grant us an irrevocable, non- exclusive, royalty-free, perpetual, worldwide license to use, modify, prepare derivative works, publish, distribute, and sublicense the Feedback; and (iv) irrevocably waive, and cause to be waived, against Native Talk and its users any claims and assertions of any moral rights contained in such Feedback. These provisions regarding Feedback shall survive any termination of your account or the Platform.</p>
    <ol start="11">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Sessions</span></li>
    </ol>
    <p><em>Hardware and Software</em>. Engaging in a Session requires compatible hardware and may require the download and installation of specified software. You are solely responsible for acquiring and installing any such hardware and software and for determining compatibility with your system, and hereby assume all risk and liability associated with such hardware and software. You acknowledge that it is your responsibility to review and comply with all applicable license agreements and other terms and conditions relating to all software you use in connection with Sessions and the Platform, generally.</p>
    <p><em>Restrictions on Use</em>. You agree to only engage in Sessions for your personal, non-commercial purposes and agree not to record, copy, redistribute, broadcast, publicly perform or publicly display any such Session, except as allowed by this Agreement.</p>
    <p><em>Session Recordings</em>. Sessions may be recorded or monitored. You hereby consent to: (i) the monitoring or recording of any Session you engage in, including your likeness therein; (ii) Native Talk copying and using such recordings for purposes of providing the Services, including without limitation for purposes of Tutor evaluation, Tutor training, dispute resolution and improving the Platform; (iii) such recording being made available to the other party to the Session, including the Student or parents of a Student; (iv) such recordings being made available for you to review; (v) such recording being used or disclosed by Native Talk to the extent required by law or legal process or to the extent Native Talk deems necessary for purposes of enforcing or protecting its rights or the rights of a third party; and (vi) as you otherwise agree (including, for Tutors, as set forth in the Tutor Addendum). You hereby waive any rights of publicity, privacy or other rights under applicable law to the extent such rights could be used to prevent Native Talk from using Session recordings for the limited purposes set forth in this subsection or as you otherwise agree (including for Tutors, in the Tutor Addendum), and hereby grant a worldwide, non-exclusive, fully paid-up, royalty-free, irrevocable, perpetual, sublicenseable, and transferable license under any intellectual property rights you may have in or to any Session recording or content therein to Native Talk to copy, modify, distribute and use such recording and content for its business purposes as set forth hereunder or as required by law or legal process.&nbsp; Notwithstanding the foregoing, you may have certain choices with respect to access to or our retention of session recordings as set forth in our Privacy Policy.</p>
    <ol start="12">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Tutor Availability and Tutor Quality</span></li>
    </ol>
    <p><em>Tutor Availability</em>. Sessions are subject to Tutor availability, and Native Talk does not guarantee that any particular (or any) Tutor will be available at any given time.</p>
    <p><em>Tutor Quality</em>. You acknowledge that Native Talk has no duty to verify any stated credentials, experience or qualifications of any Tutor, and that Native Talk does not conduct any screening of Tutors other than as expressly set forth in this Section. If you wish to submit a complaint regarding any Tutor, please contact Native Talk at <a href="mailto:support@nativetalk.live" target="_blank" rel="noopener noreferrer"><span style={{color: '#0563c1'}}>help@nativetalk.live</span></a>. Users are responsible for their communications or other interactions with other Users on or through the Platform. Native Talk reserves the right, but has no obligation, to monitor disagreements between Users, including between Students and Tutors.</p>
    <ol start="13">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Payments on the Platform</span></li>
    </ol>
    <p><em>Payment</em>. Students pay for Tutoring Services by the minute or through a payment plan as described below. Payment will occur through a third-party payment system (e.g., Stripe). All payment terms and conditions are governed by your applicable agreements with the third-party payment system, as applicable. Fees displayed to you are exclusive of any taxes that may be due in connection with such fees, and you agree to pay any such taxes that may be due, other than taxes based on Native Talk’s net income. You also agree to pay Native Talk any costs and expenses incurred by Native Talk, including reasonable attorney’s fees, in recovering any fees due hereunder.</p>
    <p><em>Payment Plans</em>. We may provide Students with an option to sign up for a payment plan in which a designated amount will be charged to a Student account on a monthly (or as otherwise designated) basis (a “Payment Plan”). By signing up for a Payment Plan and providing us with your payment account information, you are signing up to an auto-renewing subscription requiring recurring payments and agree to pay the amount designated for your particular Payment Plan on a renewing basis. If you sign up for a Payment Plan, you will be charged the first recurring payment on the date of the registration for the Payment Plan, and you will then be charged on a recurring basis until you cancel the Payment Plan or we terminate it. Your account will include information on the payment date for your Payment Plan. In some cases, your payment date may change, for example if your payment method has not successfully settled or if your Payment Plan began on a day not contained in a given month. If a payment is not successfully settled, due to expiration, insufficient funds, or otherwise, and you do not cancel your account, we may suspend your access to the Platform until we have successfully charged a valid payment method.</p>
    <p>You may cancel a Payment Plan at any time in your account settings. You must cancel a Payment Plan before it renews to avoid billing of the next installment under your particular Payment Plan.</p>
    <p><em>No Refunds</em>. Purchased minutes are non-refundable, and minutes used for a Session are non-creditable. If you have been mistakenly charged for minutes you did not purchase, you may request a refund. Refund requests will be evaluated by the third-party payment system or Native Talk. If you feel you have been charged in error, please contact Native Talk at help@nativetalk.live. A refund request must be received by Native Talk within thirty (30) days of the charge in order to be considered.</p>
    <p><em>Timing</em>. If you pay Tutors through purchased minutes, you will be charged per minute of the Session as each minute is used. If you run out of purchased minutes prior to a Session ending, the Session will terminate and you will be prompted to purchase more minutes.</p>
    <p><em>Mobile Services</em>. Use of the Apps may require usage of data services provided by your wireless service carrier. You acknowledge and agree that you are solely responsible for data usage fees and any other fees that your wireless service carrier may charge in connection with your use of the Apps.</p>
    <ol start="14">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Tutor Eligibility and Rules</span></li>
    </ol>
    <p>In addition to the other rules and prohibitions set forth in this Agreement, the following terms in this Section 14 applies to Tutors.</p>
    <p><em>Eligibility</em>. Prospective Tutors may apply to Native Talk to offer their tutoring services through the Platform. Native Talk reserves the right to request information to assess your eligibility to offer your tutoring services, and Native Talk may accept or deny your request for any reason or no reason in Native Talk’s sole discretion.</p>
    <p><em>Services To Be Performed</em>. If you are accepted as a Tutor on the Platform, you will be eligible to provide tutoring services through the Platform to Students. You agree to use your best efforts in the performance of your tutoring services, and you further agree to cooperate with Native Talk’s personnel, not to interfere with the conduct of Native Talk’s business, and to observe all Native Talk rules, regulations and security requirements with respect to the safety and safeguarding of persons and property.</p>
    <ol start="15">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Modifications and Termination of Accounts or the Platform</span></li>
    </ol>
    <p><em>Platform</em>. Native Talk may make changes to or discontinue any of the media, products or services available within the Platform at any time, and without notice. The media, products or services on the Platform may be out of date, and Native Talk makes no commitment to update these materials on the Platform. We may modify the Platform or terminate access to the Platform without prior notice, and you agree that Native Talk shall not be liable to you or any third party for any such termination.</p>
    <p><em>Account</em>. We may, in our discretion, with or without cause, with or without prior notice and at any time, decide to limit, block, suspend, deactivate, or cancel your account in whole or in part. If we exercise our discretion under this Agreement to do so, any or all of the following can occur with or without prior notice or explanation to you: (a) your account will be deactivated or suspended, your password will be disabled, and you will not be able to access the Platform or your User Content, or receive assistance from Native Talk support teams; and (b) if appropriate in our sole discretion, we may communicate to other Users that your Account has been terminated, blocked, suspended, deactivated, or cancelled, and why this action has been taken. You may cancel your use of the Platform and/or terminate your account at any time by emailing help@nativetalk.live. Please note that if your account is cancelled, we do not have an obligation to delete or return to you any User Content you have posted to the Platform unless otherwise required under applicable law. If we terminate the account of a Tutor, the applicable Tutor shall be entitled to payment for tutoring services performed by the Tutor prior to the effective date of termination, payable within sixty (60) days of termination. Such payment shall constitute full settlement of any and all claims of Tutor of every description against Native Talk.</p>
    <ol start="16">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>DMCA Notice</span></li>
    </ol>
    <p>It is Native Talk’s policy to respond to alleged infringement notices that comply with the Digital Millennium Copyright Act of 1998 ("DMCA"). If you believe that your copyrighted work has been copied in a way that constitutes copyright infringement and is accessible via the Platform, please notify Native Talk’s copyright agent as set forth in the DMCA. For your complaint to be valid under the DMCA, you must provide the following information in writing:</p>
    <ul>
      <li>An electronic or physical signature of a person authorized to act on behalf of the copyright owner.</li>
      <li>Identification of the copyrighted work that you claim has been infringed.</li>
      <li>Identification of the material that is claimed to be infringing and where it is located on the Platform.</li>
      <li>Information reasonably sufficient to permit Native Talk to contact you, such as your address, telephone number, and email address.</li>
      <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or law.</li>
      <li>A statement, made under penalty of perjury, that the above information is accurate, and that you are the copyright owner or are authorized to act on behalf of the owner.</li>
    </ul>
    <p>The above information must be submitted to the following DMCA Agent:</p>
    <p>Attn: DMCA Notice, Native Talk, Inc.</p>
    <p>340 S Lemon Ave. #4343</p>
    <p>Walnut, CA 91789</p>
    <p>UNDER FEDERAL LAW, IF YOU KNOWINGLY MISREPRESENT THAT ONLINE MATERIAL IS INFRINGING, YOU MAY BE SUBJECT TO CRIMINAL PROSECUTION FOR PERJURY AND CIVIL PENALTIES, INCLUDING MONETARY DAMAGES, COURT COSTS, AND ATTORNEYS' FEES.</p>
    <p>Please note that this procedure is exclusively for notifying Native Talk and its affiliates that your copyrighted material has been infringed. The preceding requirements are intended to comply with Native Talk’s rights and obligations under the DMCA, including 17 U.S.C. §512(c), but do not constitute legal advice. It may be advisable to contact an attorney regarding your rights and obligations under the DMCA and other applicable laws.</p>
    <p>In accordance with the DMCA and other applicable law, Native Talk has adopted a policy of, in appropriate circumstances and at Native Talk’s sole discretion, terminating the account or access of users who are deemed to be infringers or repeat infringers.</p>
    <ol start="17">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Third-Party Links and Resources</span></li>
    </ol>
    <p>The Platform may contain information and content provided by third parties and may contain links to third-party websites, and other resources that are not owned or controlled by Native Talk. Native Talk is not responsible for the availability of such external sites or resources and does not endorse and is not responsible or liable for such external sites or resources. These links and resources do not imply any endorsement by Native Talk, and Native Talk does not endorse or assume any responsibility for any such third-party sites, information, materials, products, or services. If you access a third-party website or resource from the Platform, you do so at your own risk, and you understand that this Agreement and Native Talk’s Privacy Policy do not apply to your use of such links. You expressly relieve Native Talk from any and all liability arising from your use of any third- party website, service, or content. You acknowledge and agree that Native Talk is not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources.</p>
    <ol start="18">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Disclaimers; No Warranties</span></li>
    </ol>
    <p>THE PLATFORM AND ANY THIRD-PARTY, MEDIA, SOFTWARE, SERVICES, OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE PLATFORM ARE PROVIDED “AS IS” AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, Native Talk, AND ITS SUPPLIERS, LICENSORS AND PARTNERS, DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS.&nbsp;&nbsp;</p>
    <p>Native Talk, AND ITS SUPPLIERS, LICENSORS AND PARTNERS, DO NOT WARRANT THAT THE FEATURES CONTAINED IN THE PLATFORM WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE PLATFORM, SITE, APP OR THE SERVERS THAT MAKE THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
    <p>Native Talk, AND ITS SUPPLIERS, LICENSORS AND PARTNERS, DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE PLATFORM IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU (AND NOT Native Talk NOR ITS SUPPLIERS, LICENSORS OR PARTNERS) ASSUME THE ENTIRE COST OF ANY NECESSARY SERVICING, REPAIR, OR CORRECTION. YOU UNDERSTAND AND AGREE THAT YOU DOWNLOAD, OR OTHERWISE OBTAIN MEDIA, MATERIAL, OR OTHER DATA THROUGH THE USE OF THE PLATFORM AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM SUCH MATERIAL OR DATA.</p>
    <p>CERTAIN STATE LAWS OR COUNTRIES DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.</p>
    <ol start="19">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Limitation of Liability</span></li>
    </ol>
    <p>UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL Native Talk OR ITS AFFILIATES, CONTRACTORS, EMPLOYEES, AGENTS, OR THIRD PARTY PARTNERS, LICENSORS OR SUPPLIERS, BE LIABLE TO YOU FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES THAT RESULT FROM YOUR USE OF OR THE INABILITY TO USE THE Native Talk MATERIALS ON THE PLATFORM OR THE PLATFORM ITSELF, OR ANY OTHER INTERACTIONS WITH Native Talk, EVEN IF Native Talk OR A Native Talk AUTHORIZED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, Native Talk’S LIABILITY WILL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>
    <p>IN NO EVENT SHALL Native Talk’S OR ITS AFFILIATES, CONTRACTORS, EMPLOYEES, AGENTS, OR THIRD PARTY PARTNERS OR SUPPLIERS’ TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE PLATFORM (WHETHER IN CONTRACT, TORT, WARRANTY, OR OTHERWISE) EXCEED THE GREATER OF: (A) THE TOTAL AMOUNTS YOU HAVE PAID TO Native Talk (OR ARE PAYABLE TO YOU BY Native Talk) HEREUNDER DURING THE SIX (6) MONTHS PRECEDING THE DATE OF THE CLAIM AND (B) FIFTY (50) U.S. DOLLARS.</p>
    <p>THESE LIMITATIONS SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF ANY PRODUCTS OR SERVICES SOLD OR PROVIDED TO YOU BY THIRD PARTIES OTHER THAN Native Talk AND RECEIVED BY YOU THROUGH OR ADVERTISED ON THE PLATFORM OR RECEIVED BY YOU THROUGH ANY LINKS PROVIDED ON THE PLATFORM.</p>
    <ol start="20">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Indemnification</span></li>
    </ol>
    <p>You agree to indemnify and hold Native Talk, and its affiliated companies, and its suppliers, licensors and partners, harmless from any claims, losses, damages, liabilities, including attorney’s fees, arising out of your use or misuse of the Platform, violation of the rights of any other person or entity, or any breach of this Agreement.</p>
    <p>Tutor shall further be solely liable for, and shall indemnify, defend and hold harmless Native Talk and its successors and assigns from and against any claim or liability of any kind (including penalties, fees or charges) resulting from Tutor’s failure to pay the taxes, penalties, and payments due under this Agreement, including the Tutor Addendum. Tutor shall further indemnify, defend and hold harmless Native Talk and its successors and assigns from and against any and all loss or damage resulting from any misrepresentation, or any non-fulfillment of any representation, responsibility, covenant or agreement on his part, as well as any and all acts, suits, proceedings, demands, assessments, penalties, judgments of or against Native Talk relating to or arising out of the activities of Tutor and Tutor shall pay reasonable attorneys' fees, costs and expenses incident thereto.</p>
    <p>Native Talk reserves the right, at our own expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims.</p>
    <ol start="21">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Arbitration and Class Action Waiver</span></li>
    </ol>
    <p><strong>PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.</strong></p>
    <p>Subject to restrictions and prohibitions in applicable law, you and Native Talk mutually agree to resolve any and all covered justiciable disputes between you exclusively through final and binding arbitration instead of a court or jury trial. Except as explicitly stated otherwise in this Arbitration and Class Action Waiver section, this arbitration agreement requires the arbitration of any claims that Native Talk or you may have against the other or against any of their:</p>
    <ul>
      <li>officers, directors, employees, subcontractors, or agents in their capacity as such or otherwise,</li>
      <li>direct or indirect parents and subsidiaries, and</li>
      <li>affiliates, agents, successors or assigns,</li>
    </ul>
    <p>each and all of which may enforce this arbitration agreement as direct or third-party beneficiaries.</p>
    <p><em>Scope</em>. This arbitration agreement is governed by the Federal Arbitration Act (9 U.S.C. §§ 1-16) and applies to any and all claims or controversies, past, present or future, arising out of or relating to this Agreement, this arbitration agreement, or any access or use of the Platform, including without limitation, Tutor’s independent contractor classification, Tutor’s provision of services, Student’s receipt of services, any payments made to Tutor through the Platform or arising out of or relating to the acceptance or performance of services arranged through the Platform, the termination of this Agreement, claims of harassment, retaliation, or discrimination and all other aspects of a Student’s or Tutor’s relationship (or the termination of its relationship) with Native Talk, whether arising under federal, state or local statutory and/or common law. You and Native Talk agree that the mutual obligations contained in this Agreement and to arbitrate disputes provide adequate consideration for this arbitration agreement. Without limitation, claims covered by this arbitration requirement include any statutory claims under state or federal law, including, but not limited to, claims under Title VII of the Civil Rights Act of 1964, the Americans with Disabilities Act of 1990, the Age Discrimination in Employment Act of 1967, the Older Workers Benefit Protection Act, the California Fair Employment and Housing Act, the California Labor Code, claims of harassment, discrimination or wrongful termination and any statutory claims.</p>
    <p><em>Initial Dispute Resolution</em>: Most disputes can be resolved without resort to litigation. You can reach Native Talk’s support department at help@nativetalk.live. Except for intellectual property and small claims court claims, the parties agree to use their best efforts to settle any dispute, claim, question, or disagreement directly through consultation with the Native Talk support department, and good faith negotiations shall be a condition to either party initiating a lawsuit or arbitration.</p>
    <p><em>Demand for Arbitration</em>. If the parties do not reach an agreed-upon solution within a period of thirty (30) days from the time informal dispute resolution is initiated under the Initial Dispute Resolution provision above, then either party may initiate binding arbitration as the sole means to resolve claims, subject to the terms set forth below. If either party initiates arbitration, the initiating party must notify the other party in writing via U.S. Mail, or hand delivery within the applicable statute of limitations period. This demand for arbitration must include: (i) the name and address of the party seeking arbitration; (ii) a statement of the legal and factual basis of the claim; and (iii) a description of the remedy sought. Any demand for arbitration by Student or Tutor must be delivered to Native Talk at 340 S Lemon Ave. #4343, Walnut, CA 91789. The Arbitrator will resolve all disputes regarding the timeliness or propriety of the demand for arbitration. The parties understand that, absent this mandatory arbitration provision, they would have the right to sue in court and have a jury trial. They further understand that, in some instances, the costs of arbitration could exceed the costs of litigation and the right to discovery may be more limited in arbitration than in court.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
    <p><em>Class and Collective Action Waivers</em>. <strong>You and</strong><strong>Native Talk mutually agree that by entering into this arbitration agreement to arbitrate, both waive their right to have any covered dispute or claim brought, heard or arbitrated as a class action and/or collective action, and an Arbitrator will not have any authority to hear or arbitrate any class and/or collective claim (“Class Action Waiver”).</strong> Notwithstanding any other clause contained in this arbitration agreement or the AAA Rules, as defined below, any claim that all or part of this Class Action Waiver is unenforceable, unconscionable, void, or voidable may be determined only by a court of competent jurisdiction and not by an Arbitrator. The Class Action Waiver will be severable from this arbitration agreement in any case, in which (1) the dispute is filed as a class and/or collective action and (2) there is a final judicial determination that all or part of the Class Action Waiver is invalid, unenforceable, unconscionable, void, or voidable. In such case, the class and/or collective action to that extent must be litigated in a civil court of competent jurisdiction, but the portion of the Class Action Waiver that is enforceable shall be enforced in arbitration.&nbsp;&nbsp;</p>
    <p><em>Arbitration Procedures</em>. Except as otherwise stated in this arbitration agreement, any arbitration shall be governed by the American Arbitration Association Commercial Arbitration Rules (“AAA Rules”), subject to the following:</p>
    <ul>
      <li>The arbitration shall be heard by one Arbitrator selected in accordance with the AAA Rules. Unless the parties agree otherwise, the Arbitrator shall be an attorney experienced in the law in the underlying dispute and licensed to practice law in the state in which the arbitration is convened or a former judge from any jurisdiction.&nbsp;&nbsp;</li>
      <li>If you are a resident of the United States, arbitration may take place in the county where you reside at the time of filing. For individuals residing outside the United States, arbitration shall be initiated in the State of California, United States of America. You and Native Talk further agree to submit to the personal jurisdiction of any federal or state court in Los Angeles County, California in order to compel arbitration, to stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.</li>
      <li>The parties agree that they will equally split all of the Arbitrator’s fees and costs except (1) where applicable law provides otherwise, as determined by the Arbitrator; or (2) the parties otherwise agree. Each party will pay for its own costs and attorneys’ fees, if any. However, if any party prevails on a claim that affords the prevailing party attorneys’ fees, the Arbitrator may award reasonable fees to the prevailing party as provided by law. If the law (including the common law) of the jurisdiction in which the arbitration is held requires a different allocation of arbitral fees and costs for this arbitration agreement to be enforceable, then such law will be followed, and any disputes in that regard will be resolved by the Arbitrator.</li>
      <li>The Arbitrator is authorized to issue orders (including subpoenas to third parties) allowing the parties to conduct discovery sufficient to allow each party to prepare that party’s claims and/or defenses, taking into consideration that arbitration is designed to be a speedy and efficient method for resolving disputes.</li>
      <li>Except as provided in the Class Action Waiver, the Arbitrator may award all remedies to which a party is entitled under applicable law and which would otherwise be available in a court of law, but shall not be empowered to award any remedies that would not have been available in a court of law for the claims presented in arbitration. The Arbitrator shall apply the state or federal substantive law, or both, as is applicable.</li>
      <li>The Arbitrator may hear motions to dismiss and/or motions for summary judgment and will apply the standards of the Federal Rules of Civil Procedure governing such motions.</li>
      <li>The Arbitrator’s decision or award shall be in writing with findings of fact and conclusions of law. Judgment may be entered on the Arbitrator’s decision or award in any court having jurisdiction.&nbsp;&nbsp;</li>
      <li>The AAA Rules referenced herein may be found at www.adr.org or by searching for “AAA Commercial Arbitration Rules” using a service such as www.Google.com or www.Bing.com.</li>
    </ul>
    <p><em>Exception: Litigation of Intellectual Property and Small Claims Court Claims.</em> Notwithstanding the parties' decision to resolve all disputes through arbitration, either party may bring enforcement actions, validity determinations or claims arising from or relating to theft, piracy or unauthorized use of intellectual property in state or federal court or in the U.S. Patent and Trademark Office to protect its intellectual property rights ("intellectual property rights" means patents, copyrights, moral rights, trademarks, and trade secrets, but not privacy or publicity rights). Either party may also seek relief in a small claims court for disputes or claims within the scope of that court's jurisdiction.</p>
    <p><em>30-Day Right to Opt Out.</em> Unless you have previously agreed to an arbitration and class action waiver provision for disputes with Native Talk, you have the right to opt out and not be bound by the arbitration and class action waiver provisions set forth above by sending (from the email address you used to register for your account) written notice of your decision to opt out to help@nativetalk.live with the subject line, "ARBITRATION AND CLASS ACTION WAIVER OPT-OUT." The notice must be sent within thirty (30) days of your first use of the Platform or the effective date of the first Agreement containing an Arbitration and Class Action Waiver section, whichever is later; otherwise, you shall be bound to arbitrate disputes in accordance with the terms of these paragraphs. If you opt out of these arbitration provisions, Native Talk also will not be bound by them.</p>
    <p><em>Changes to This Section</em>. Native Talk will provide thirty (30) days' notice of any changes affecting the substance of this section by posting on the Platform, sending you a message, or otherwise notifying you when you are logged into your account. Amendments affecting the substance of this section will become effective thirty (30) days after they are posted on the Platform or sent to you. Changes to this section will otherwise apply prospectively only to claims arising after the thirtieth (30th) day. If a court or arbitrator decides that this subsection on "Changes to This Section" is not enforceable or valid, then this subsection shall be severed from the section entitled “Arbitration and Class Action Waiver,” and the court or arbitrator shall apply the first Arbitration and Class Action Waiver section in existence after you began using the Platform.</p>
    <p>Survival. This arbitration agreement survives after the termination of this Agreement and/or after you cease any relationship with Native Talk.</p>
    <ol start="22">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>General&nbsp;</span></li>
    </ol>
    <p><em>Notices</em>. Under this Agreement, you consent to receive communications from Native Talk electronically. Native Talk will communicate with you by e-mail or by posting notices on the Sites or Apps. You agree that all agreements, notices, disclosures, and other communications that Native Talk provides to you electronically satisfy any legal requirement that such communications be in writing. Except as provided herein, all notices and communications to Native Talk shall be in writing and shall be deemed to have been duly given or made (i) with delivery by hand, when delivered, (ii) with delivery by certified or registered mail, postage prepaid; or (iii) with delivery by internationally recognized overnight courier. Notices to Native Talk shall be sent to 340 S Lemon Ave #4343, Walnut CA 91789.</p>
    <p><em>Language</em>. Any action brought under this Agreement shall be conducted in the English language. If you are located in France or Quebec, Canada, the following clause applies: The parties hereby confirm that they have requested that this Agreement be drafted in English. Les parties contractantes confirment qu'elles ontexigé que le présent contrat et tous les documents associés soient redigés en anglais.</p>
    <p><em>Complete Agreement</em>. This Agreement (including the Tutor Addendum for Tutors) contains the entire understanding between the parties and supersedes, replaces and takes precedence over any prior understanding or oral or written agreement between the parties respecting the subject matter of this Agreement. There are no representations, agreements, arrangements, nor understandings, oral or written, between the parties relating to the subject matter of this Agreement that are not fully expressed herein.</p>
    <p><em>Severability</em>. In the event any provision of this Agreement shall be held invalid, the same shall not invalidate or otherwise affect in any respect any other term or terms of this Agreement, which term or terms shall remain in full force and effect.</p>
    <p><em>Transfer and Assignment</em>. This Agreement, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Native Talk without restriction. Any attempted transfer or assignment in violation hereof shall be null and void. The terms of this Agreement bind and inure to the benefit of each party and the party’s successors and permitted assigns.</p>
    <p><em>Survival</em>. Sections 3, 6, 8, 10-11, 13, 15-22 will survive any termination of this Agreement.</p>
    <p><em>Non-Waiver</em>. No delay or omission by Native Talk in exercising any right under this Agreement shall operate as a waiver of that or any other right. A waiver or consent given by Native Talk on any one occasion shall be effective only in that instance and shall not be construed as a bar or waiver of any right on any other occasion.</p>
    <p><em>Headings</em>. The headings and other captions in this Agreement are included solely for convenience of reference and will not control the meaning and interpretation of any provision of this Agreement.</p>
    <p><em>Governing Law; Jurisdiction</em>. Other than the Arbitration and Class Action Waiver provision, which shall be governed by the Federal Arbitration Act, this Agreement will in all respects be governed by the laws of the State of California, United States of America, without reference to its principles of conflicts of laws.&nbsp;&nbsp;</p>
    <p><em>Contact Us</em>. Please contact us at help@nativetalk.live with any questions regarding this Agreement.</p>
    <ol start="23">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Apple iOS&nbsp;&nbsp;</span></li>
    </ol>
    <p>If you access our Platform using a mobile application that you download, access and/or use and that runs on Apple’s iOS operating system (an “iOS App”), you acknowledge and agree that:</p>
    <ul>
      <li>the iOS App may only be accessed and used on a device owned or controlled by you and using Apple’s iOS operating system;</li>
      <li>the terms of this Agreement are between you and Native Talk, and not with Apple;</li>
      <li>Apple has no obligation at all to provide any support or maintenance services in relation to the iOS App, and if you have any maintenance or support questions in relation to the iOS App, please contact Native Talk, not Apple;</li>
      <li>except as otherwise expressly set forth in this Agreement, any claims relating to the possession or use of the iOS App are between you and Native Talk (and not between you, or anyone else, and Apple);</li>
      <li>in the event of any claim by a third party that your possession or use (in accordance with this Agreement) of the iOS App infringes any intellectual property rights, Apple will not be responsible or liable to you in relation to that claim; and</li>
      <li>although this Agreement entered into between you and Native Talk (and not Apple), Apple, as a third-party beneficiary under this Agreement, will have the right to enforce these terms against you.</li>
    </ul>
    <p>In addition, you represent and warrant that:</p>
    <ul>
      <li>you are not, and will not be, located in any country that is the subject of a United States Government embargo or that has been designated by the United States Government as a “terrorist supporting” country;</li>
      <li>you are not listed on any United States Government list of prohibited or restricted parties; and</li>
      <li>if the iOS App does not conform to any warranty applying to it, you may notify Apple, which will then refund the purchase price of the iOS App (if any) to you. Subject to that, and to the maximum extent permitted by law, Apple does not give or enter into any warranty, condition or other term in relation to the iOS App and will not be liable to you for any claims, losses, costs or expenses of whatever nature in relation to the iOS App or as a result of you or anyone else using the iOS App or relying on any of its content.</li>
    </ul>
    <ol start="24">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Google App.&nbsp;</span></li>
    </ol>
    <p>If you access our Platform on a mobile application that you download, access, and/or use from the Google Play Store (“Google-Sourced Software”): (i) you acknowledge that this Agreement is between you and Native Talk only, and not with Google, Inc. (“Google”); (ii) your use of Google-Sourced Software must comply with Google’s then-current Google Play Store Terms of Service; (iii) Google is only a provider of the Google Play Store where you obtained the Google-Sourced Software; (iv) Native Talk, and not Google, is solely responsible for its Google-Sourced Software; (v) Google has no obligation or liability to you with respect to Google-Sourced Software or this Agreement; and (vi) you acknowledge and agree that Google is a third-party beneficiary to this Agreement as it relates to Native Talk’s Google-Sourced Software.</p>
  </div>
);

export default TermsPage;
