const CourseActionTypes = {
  CREATE_COURSE_START: 'CREATE_COURSE_START',
  CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  CREATE_COURSE_FAILURE: 'CREATE_COURSE_FAILURE',
  UPDATE_COURSE_START: 'UPDATE_COURSE_START',
  UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',
  UPDATE_COURSE_FAILURE: 'UPDATE_COURSE_FAILURE',
  FETCH_COURSES_START: 'FETCH_COURSES_START',
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
  FETCH_COURSES_FAILURE: 'FETCH_COURSES_FAILURE',
  FETCH_COURSE_BY_ID_START: 'FETCH_COURSE_BY_ID_START',
  FETCH_COURSE_BY_ID_SUCCESS: 'FETCH_COURSE_BY_ID_SUCCESS',
  FETCH_COURSE_BY_ID_FAILURE: 'FETCH_COURSE_BY_ID_FAILURE',
}

export default CourseActionTypes;
