const CourseActionTypes = {
  CREATE_COURSE_START: 'CREATE_COURSE_START',
  CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  CREATE_COURSE_FAILURE: 'CREATE_COURSE_FAILURE',
  UPDATE_COURSE_START: 'UPDATE_COURSE_START',
  UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',
  UPDATE_COURSE_FAILURE: 'UPDATE_COURSE_FAILURE',
}

export default CourseActionTypes;
