const InstructorActionTypes = {
  CREATE_COURSE_START: 'CREATE_COURSE_START',
  CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  CREATE_COURSE_FAILURE: 'CREATE_COURSE_FAILURE',
  EDIT_COURSE_START: 'EDIT_COURSE_START',
  EDIT_COURSE_SUCCESS: 'EDIT_COURSE_SUCCESS',
  EDIT_COURSE_FAILURE: 'EDIT_COURSE_FAILURE',
}

export default InstructorActionTypes;
