import React from 'react';

import './addendum-page.styles.scss';

const AddendumPage = () => (
  <div className='container px-xs mt-xs'>
    <p style={{textAlign: 'center', marginBottom: '5px'}}><span style={{fontWeight: 'bold'}}>Native Talk Inc.</span></p>
    <p style={{textAlign: 'center', marginTop: '0px'}}><span style={{fontWeight: 'bold'}}>Tutor Addendum</span></p>
    <p>Last Updated: November 16, 2020</p>
    <p>This Tutor Addendum is an addendum to the User Agreement between Tutors and Native Talk Inc. (“Native Talk,” “we,” “us,” or “our”), and it sets forth additional terms and conditions that are applicable to your access, registration, and use of the Platform in your capacity as a Tutor. Capitalized terms herein have the meaning set forth in the Agreement. To the extent of a conflict between any terms of this Tutor Addendum and any terms of the Agreement, the terms of this Tutor Addendum shall control.</p>
    <ol start="1">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Independent Contractor&nbsp;&nbsp;</span></li>
    </ol>
    <p><span style={{fontStyle: 'italic'}}>Independent Contractor Status</span>. It is the express intention of the parties to this Tutor Addendum that Tutor is an independent contractor and not an employee, agent, joint venturer or partner of Native Talk for any purposes whatsoever. Tutor shall not be entitled to any benefits that Native Talk may make available to employees from time to time. Tutor shall be solely responsible for all state and federal income taxes, unemployment insurance and social security taxes and for maintaining adequate workers' compensation insurance coverage.</p>
    <p><span style={{fontStyle: 'italic'}}>Performance of Services</span>. Tutor shall have the right to control and determine the time, place, methods, manner and means of performing tutoring services on the Platform (the “Tutor’s Services”). In performing the Tutor’s Services, the amount of time Tutor uses the Platform on any given day will be entirely within Tutor's control. Tutor will provide all equipment and supplies required to perform the Tutor’s Services, including supplying the electronic device to operate the App or the Site.</p>
    <p><span style={{fontStyle: 'italic'}}>Teaching Discretion</span>. In the performance of the Tutor’s Services, Tutor has the authority to control and direct the performance of the details of the Tutor’s Services, including the specific lessons, vocabulary or exercises used by Tutor in the execution of the Tutor’s Services. However, the Tutor’s Services contemplated by this Addendum must meet Native Talk’s quality and service standards and shall be subject to Native Talk’s general right of inspection and supervision.</p>
    <p><span style={{fontStyle: 'italic'}}>Non-Exclusivity and Non-Solicitation</span>. Tutor retains the right to contract with other companies or entities for his or her consulting services without restriction. Likewise, Native Talk retains a reciprocal right to contract with other companies and/or individuals for consulting services without restriction. However, Tutor shall not directly or indirectly, either alone or in association with others, during the Tutor’s offering or provision of the Tutor’s Services on the Platform and for six (6) months thereafter, solicit, induce or attempt to induce, any Student to terminate his or her relationship or other engagement with Native Talk and receive Tutor’s Services outside the App or the Site.</p>
    <p><span style={{fontStyle: 'italic'}}>Scope of Authority</span>. Tutor is not authorized to transact business, incur obligations, sell goods, receive payments, solicit orders or assign or create any obligation of any kind, express or implied, on behalf of Native Talk or any of Native Talk’s related or affiliated entities, or to bind in any way whatsoever, or to make any promise, warranty or representation on behalf of Native Talk or any of Native Talk’s related or affiliated entities with respect to any matter, except as expressly authorized in a writing signed by an authorized representative of Native Talk. Tutor shall not use Native Talk’s trade names, trademarks, service names or servicemarks without the prior written approval of Native Talk.</p>
    <p><span style={{fontStyle: 'italic'}}>Federal Tax Return Filing</span>. Tutor agrees to report income received from the Company for consulting services under this Addendum consistent with the reporting requirements of an independent contractor.</p>
    <ol start="2">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Priority Hours</span></li>
    </ol>
    <p>Tutor understands that as an independent contractor Tutor has complete control over Tutor's own schedule. However, at Native Talk’s own discretion, Native Talk may grant Tutor the option to sign up for Priority Hours through Tutor’s account (“Priority Hours”). Native Talk does not guarantee that Priority Hours will be available or that Tutor will have the Priority Hours feature enabled in Tutor’s account, nor that Students will be available during any Priority Hour. If a Tutor signs up for a Priority Hour and completes his or her full Priority Hour, Native Talk agrees to compensate Tutor for at least 15 minutes of Tutor’s Services. Tutors can cancel any reserved Priority Hour prior to the start of such Priority Hour, but is advised to attend the full Priority Hour once a Priority Hour that has not been canceled begins. Native Talk reserves the right to cancel Priority Hours at any time.</p>
    <ol start="3">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Payment</span></li>
    </ol>
    <p>In consideration of Tutor’s performance of Tutor’s Services, Native Talk shall pay to Tutor a fee equal to $0.17 per minute spent performing Tutor’s Services through the App or the Site, as recorded by Native Talk in its sole discretion. Native Talk shall pay Tutor within thirty (30) days after Tutor has performed at least $20.00 of Tutor’s Services. However, if Tutor does not perform at least $20.00 of Tutor’s Services within any sixty (60)-day period, Native Talk shall pay Tutor for Tutor’s Services in full. All payment by Native Talk to Tutor shall be made through a third-party payment processor (e.g. Stripe, PayPal) designated by Native Talk in Native Talk’s sole discretion. All payment terms and conditions are governed by your applicable agreements with the third-party payment system, as applicable. Tutor has all necessary rights in such account with the third-party payment processor to authorize Native Talk to make payments to such account, and Tutor agrees that payments made to the account designated by Tutor on the Platform satisfies all of Native Talk’s obligations hereunder. Native Talk is not responsible for any issues that Tutor may experience with Stripe or any other third-party payment processor. If Tutor has any questions concerning the third-party payment processor and its practices, Tutor may contact the third-party payment processor directly.</p>
    <ol start="4">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Proprietary Information</span></li>
    </ol>
    <p>Without limiting the Agreement, Tutor agrees that all files, documents, letters, memoranda, reports, records, data, sketches, drawings, models, laboratory notebooks, program listings, computer equipment or devices, computer programs or other written, photographic, or other tangible material containing Native Talk proprietary information, whether created by Tutor or others, which shall come into his custody or possession, shall be and are the exclusive property of Native Talk to be used by Tutor only in the performance of his duties for Native Talk and shall not be copied or removed from Native Talk premises except in the pursuit of the business of Native Talk. All such materials or copies thereof and all tangible property of Native Talk in the custody or possession of Tutor shall be delivered to Native Talk, upon the earlier of (i) a request by Native Talk or (ii) the termination of the Agreement. After such delivery, Tutor shall not retain any such materials or copies thereof or any such tangible property.</p>
    <p>Tutor’s obligations with respect to proprietary information of Native Talk also extends to such types of information, materials and tangible property of customers of Native Talk or suppliers to Native Talk or other third parties who may have disclosed or entrusted the same to Native Talk or to Tutor.</p>
    <ol start="5">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Student Data</span></li>
    </ol>
    <p>Tutor understands that in the course of offering or providing Tutor’s Services to Students, Tutor may obtain personal information from Students, including without limitation access to recordings of Sessions, the Student’s age, geographic location, profession, and/or language abilities (collectively, “Student Data”). Tutor agrees that he or she will only access or otherwise use or process Student Data solely to provide Tutor’s Services. Tutor may use or disclose Student Data for other purposes only if explicitly authorized by the applicable Student or as required by applicable law. Without limiting Tutor’s other obligations as a “controller” under the GDPR, and a “business” under the CCPA (if applicable to Tutor), Tutor agrees to secure and protect Student Data as required under applicable law.&nbsp;</p>
    <ol start="6">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Tutor Release</span></li>
    </ol>
    <p>Tutor&nbsp; grants Native Talk the right and permission to use in perpetuity, Tutor’s name, likeness, image, voice, recorded voice, appearance, recorded appearance (including through video or photography), biographical information, performance and/or testimonial(s) (collectively, “Appearance”) in any manner and in any media, now known or later developed, throughout the world, at any time, for the purpose of advertising and publicizing the Native Talk’s products and services, without review, permission or compensation of any amount or kind whatsoever. Native Talk shall have complete ownership of any recording, product, copy, presentation or other material or file containing or featuring Tutor’s Appearance (“Ad Product”), including copyright interests, and Tutor acknowledges it has no interest or ownership in the Ad Product (or any portion thereof) or its copyright. This grant includes without limitation the right for Native Talk to edit, abridge, augment, title, or create a compilation from Tutor’s Appearance in whole or part as Native Talk may elect in its sole discretion.&nbsp;</p>
    <ol start="7">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Developments</span></li>
    </ol>
    <p>Tutor will make full and prompt disclosure to Native Talk of all inventions, creations, improvements, discoveries, methods, developments, software and works of authorship, whether patentable or not, that are created, made, conceived or reduced to practice by him or under his direction or jointly with others during the period in which Tutor is eligible to offer Tutor’s Services on the Platform (the “Service Period”), whether or not during normal working hours or on the premises of Native Talk (all of which are collectively referred to in this Addendum as “Developments”). Tutor agrees to assign and does hereby assign to Native Talk (or any person or entity designated by Native Talk) all of his right, title and interest in and to all Developments and all related patents, patent applications, copyrights and copyright applications. However, the previous sentence shall not apply to Developments that do not relate to the present or planned business or research and development of Native Talk and that are made and conceived by Tutor not during normal working hours, not on Native Talk’s premises and not using Native Talk’s tools, devices, equipment or Native Talk Materials. Tutor understands that, to the extent this Addendum shall be construed in accordance with the laws of any state that precludes a requirement that an individual assign certain classes of inventions, this Section 5 shall be interpreted not to apply to any invention that a court rules and/or Native Talk agrees falls within such classes. Tutor hereby waives all claims to moral rights in any Developments. Tutor agrees to cooperate fully with Native Talk, both during and after the Service Period, with respect to the procurement, maintenance, and enforcement of copyrights, patents and other intellectual property rights (both in the United States and foreign countries) relating to Developments. Tutor shall sign all papers, including, without limitation, copyright applications, patent applications, declarations, oaths, formal assignments, assignments of priority rights, and powers of attorney, which Native Talk may deem necessary or desirable in order to protect its rights and interests in any Development. Tutor further agrees that if Native Talk is unable, after reasonable effort, to secure the signature of Tutor on any such papers, any executive officer of Native Talk shall be entitled to execute any such papers as the agent and the attorney-in-fact of Tutor, and Tutor hereby irrevocably designates and appoints each executive officer of Native Talk as his agent and attorney-in-fact to execute any such papers on his behalf, and to take any and all actions as Native Talk may deem necessary or desirable in order to protect its rights and interests in any Development, under the conditions described in this sentence.</p>
    <ol start="8">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Content of Students Under the Age of 13</span></li>
    </ol>
    <p>Tutor shall comply with the U.S. Children’s Online Privacy Protection Act (“COPPA”), 15 U.S.C. §§ 6501-6508, and the COPPA Rule, 16 CFR Part 312, when providing Tutor’s Services to Students Minor Students. As used herein, Minor Students shall be Students under the age of 13 in the United States, Students under the age of 16 in the European Union, and Students under the age of 14 in Spain or South Korea. In accordance with COPPA, the COPPA Rule, and this Addendum, Tutor shall not use any content or information obtained from Minor Students provided during video chat sessions, through messaging with Minor Students, or otherwise provided by Minor Students to Tutor or obtained by Tutor, except solely to provide Tutor’s Services to Minor Students. Tutor shall not disclose any content or information of or about Minor Students to any third parties other than Native Talk, and Tutor agrees to delete or destroy any content or information of or about Minor Students upon request of Native Talk.</p>
    <ol start="9">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Remedies</span></li>
    </ol>
    <p>Tutor acknowledges that any breach of the provisions of Sections 4 or 5 of this Addendum shall result in serious and irreparable injury to Native Talk for which Native Talk cannot be adequately compensated by monetary damages alone. Tutor agrees, therefore, that, in addition to any other remedy it may have, Native Talk shall be entitled to enforce the specific performance of this Addendum by Tutor and to seek both temporary and permanent injunctive relief (to the extent permitted by law) without the necessity of proving actual damages or posting a bond.</p>
    <ol start="10">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Other Agreements</span></li>
    </ol>
    <p>Tutor hereby represents that, except as Tutor has disclosed in writing to Native Talk, Tutor is not bound by the terms of any agreement with any third party to refrain from using or disclosing any trade secret or confidential or proprietary information in the course of his consultancy with Native Talk, to refrain from competing, directly or indirectly, with the business of such third party or to refrain from soliciting employees, customers or suppliers of such third party. Tutor further represents that his performance of all the terms of the Agreement and this Addendum and the performance of Tutor’s Services as a Tutor of Native Talk do not and will not breach any agreement with any third party to which Tutor is a party (including without limitation any nondisclosure or non-competition agreement), and that Tutor will not disclose to Native Talk or induce Native Talk to use any confidential or proprietary information or material belonging to any current or previous employer or others.</p>
    <ol start="11">
      <li style={{fontWeight: 'bold'}}><span style={{fontWeight: 'bold'}}>Modifications</span></li>
    </ol>
    <p>Native Talk may make modifications to this Addendum at any time. Except as explicitly provided in this Addendum, such modifications will be effective as to existing Tutors after Native Talk provides notice of the modifications, either through the Platform user interface or sent to the e-mail address associated with your user account; and when you opt-in or otherwise expressly agree to the modifications or a version of this Addendum incorporating the modifications. If you provide written notice that you do not accept a proposed modification or decline to expressly agree to a proposed modification Native Talk may terminate the Agreement and your use of the Platform.</p>
  </div>
)

export default AddendumPage;
