const InstructorLessonActionTypes = {
  FETCH_INSTRUCTOR_LESSONS_START: 'FETCH_INSTRUCTOR_LESSONS_START',
  FETCH_INSTRUCTOR_LESSONS_SUCCESS: 'FETCH_INSTRUCTOR_LESSONS_SUCCESS',
  FETCH_INSTRUCTOR_LESSONS_FAILURE: 'FETCH_INSTRUCTOR_LESSONS_FAILURE',
  FETCH_INSTRUCTOR_LESSON_START: 'FETCH_INSTRUCTOR_LESSON_START',
  FETCH_INSTRUCTOR_LESSON_SUCCESS: 'FETCH_INSTRUCTOR_LESSON_SUCCESS',
  FETCH_INSTRUCTOR_LESSON_FAILURE: 'FETCH_INSTRUCTOR_LESSON_FAILURE',
  CREATE_INSTRUCTOR_LESSON_START: 'CREATE_INSTRUCTOR_LESSON_START',
  CREATE_INSTRUCTOR_LESSON_SUCCESS: 'CREATE_INSTRUCTOR_LESSON_SUCCESS',
  CREATE_INSTRUCTOR_LESSON_FAILURE: 'CREATE_INSTRUCTOR_LESSON_FAILURE',
  UPDATE_INSTRUCTOR_LESSON_START: 'UPDATE_INSTRUCTOR_LESSON_START',
  UPDATE_INSTRUCTOR_LESSON_SUCCESS: 'UPDATE_INSTRUCTOR_LESSON_SUCCESS',
  UPDATE_INSTRUCTOR_LESSON_FAILURE: 'UPDATE_INSTRUCTOR_LESSON_FAILURE',
}

export default InstructorLessonActionTypes;
