const InstructorActionTypes = {
  FETCH_INSTRUCTOR_DETAILS_START: 'FETCH_INSTRUCTOR_DETAILS_START',
  FETCH_INSTRUCTOR_DETAILS_SUCCESS: 'FETCH_INSTRUCTOR_DETAILS_SUCCESS',
  FETCH_INSTRUCTOR_DETAILS_FAILURE: 'FETCH_INSTRUCTOR_DETAILS_FAILURE',
  UPDATE_INSTRUCTOR_DETAILS_START: 'UPDATE_INSTRUCTOR_DETAILS_START',
  UPDATE_INSTRUCTOR_DETAILS_SUCCESS: 'UPDATE_INSTRUCTOR_DETAILS_SUCCESS',
  UPDATE_INSTRUCTOR_DETAILS_FAILURE: 'UPDATE_INSTRUCTOR_DETAILS_FAILURE',
  UPDATE_INSTRUCTOR_RATING_START: 'UPDATE_INSTRUCTOR_RATING_START',
  UPDATE_INSTRUCTOR_RATING_SUCCESS: 'UPDATE_INSTRUCTOR_RATING_SUCCESS',
  UPDATE_INSTRUCTOR_RATING_FAILURE: 'UPDATE_INSTRUCTOR_RATING_FAILURE',
}

export default InstructorActionTypes;
