const UserActionTypes = {
  RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',
  CHECK_USER_SESSION_START: 'CHECK_USER_SESSION_START',
  CHECK_USER_SESSION_SUCCESS: 'CHECK_USER_SESSION_SUCCESS',
  CHECK_USER_SESSION_FAILURE: 'CHECK_USER_SESSION_FAILURE',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  PASSWORD_RESET_START: 'PASSWORD_RESET_START',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILURE: 'PASSWORD_RESET_FAILURE',
}

export default UserActionTypes;
