const UIActionTypes = {
  UI_ACTION_START: 'UI_ACTION_START',
  UI_ACTION_STOP: 'UI_ACTION_STOP',
  UI_SUB_ACTION_START: 'UI_SUB_ACTION_START',
  UI_SUB_ACTION_STOP: 'UI_SUB_ACTION_STOP',
}

export default UIActionTypes;
