const StudentCourseActionTypes = {
  FETCH_STUDENT_COURSES_START: 'FETCH_STUDENT_COURSES_START',
  FETCH_STUDENT_COURSES_SUCCESS: 'FETCH_STUDENT_COURSES_SUCCESS',
  FETCH_STUDENT_COURSES_FAILURE: 'FETCH_STUDENT_COURSES_FAILURE',
  FETCH_STUDENT_COURSE_START: 'FETCH_STUDENT_COURSE_START',
  FETCH_STUDENT_COURSE_SUCCESS: 'FETCH_STUDENT_COURSE_SUCCESS',
  FETCH_STUDENT_COURSE_FAILURE: 'FETCH_STUDENT_COURSE_FAILURE',
  CREATE_STUDENT_COURSE_START: 'CREATE_STUDENT_COURSE_START',
  CREATE_STUDENT_COURSE_SUCCESS: 'CREATE_STUDENT_COURSE_SUCCESS',
  CREATE_STUDENT_COURSE_FAILURE: 'CREATE_STUDENT_COURSE_FAILURE',
  UPDATE_STUDENT_COURSE_START: 'UPDATE_STUDENT_COURSE_START',
  UPDATE_STUDENT_COURSE_SUCCESS: 'UPDATE_STUDENT_COURSE_SUCCESS',
  UPDATE_STUDENT_COURSE_FAILURE: 'UPDATE_STUDENT_COURSE_FAILURE',
}

export default StudentCourseActionTypes;
