const PaymentHistoryActionTypes = {
  FETCH_PAYMENT_HISTORY_START: 'FETCH_PAYMENT_HISTORY_START',
  FETCH_PAYMENT_HISTORY_SUCCESS: 'FETCH_PAYMENT_HISTORY_SUCCESS',
  FETCH_PAYMENT_HISTORY_FAILURE: 'FETCH_PAYMENT_HISTORY_FAILURE',
  UPDATE_PAYMENT_HISTORY_START: 'UPDATE_PAYMENT_HISTORY_START',
  UPDATE_PAYMENT_HISTORY_SUCCESS: 'UPDATE_PAYMENT_HISTORY_SUCCESS',
  UPDATE_PAYMENT_HISTORY_FAILURE: 'UPDATE_PAYMENT_HISTORY_FAILURE',
}

export default PaymentHistoryActionTypes;
